### ISSUE TITLE
Documentation feedback

### ISSUE THREAD

**Issue by yzhong94** [TexasInstruments/azure-iot-pal-simplelink#2]
- Broken links on main readme: [Setup your IoT Hub](https://github.com/TexasInstruments/azure-iot-pal-simplelink/blob/setup_iothub.md), [Provisioning your device and get its credentials ](https://github.com/TexasInstruments/azure-iot-pal-simplelink/blob/manage_iot_hub.md)]
- Using DPS - if the bool is set to "true", building the simplehttp sample fails, are there additional steps for DPS?

**Comment by vincent-ti** [comment]
Thanks Yi for letting us know. We will be updating the README shortly to reflect the latest information (hopefully later today).

For DPS support, it is best to download and install the TI SimpleLink SDK Plugin for Microsoft Azure: http://www.ti.com/tool/SIMPLELINK-SDK-PLUGIN-FOR-AZUREIOT. The example `prov_dev_client_ll_sample` in the Plugin uses DPS and its README would be a more suitable starting point. Once the libraries are built with DPS enabled, the application must implement a custom HSM interface, or else it'd fail to build. The simplesample_http example does not support DPS, which is why you encountered the build failure.

**Comment by yzhong94** [comment]
Thank you!  Will try this out :)

**Comment by vincent-ti** [comment]
Fyi README has now been updated.
